# netlify.toml

# --- Build Configuration ---
[build]
  # This tells Netlify to create .br files during the build process
  command = "npm run build"
  publish = "dist"


# --- Caching Headers for Models ---
[[headers]]
  # This rule applies to all .br files in your models folder
  for = "/models/*.onnx.br"
  [headers.values]
    # Cache for 1 year, immutable content
    Cache-Control = "public, max-age=31536000, immutable"
    # Tell the browser the content is Brotli-compressed
    Content-Encoding = "br"
    # Set the correct MIME type
    Content-Type = "application/octet-stream"

# --- Caching Headers for Other Static Assets ---
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# --- Caching Headers for API-like JSON files ---
[[headers]]
  for = "/test_split.json"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"