# netlify.toml

# --- Build Configuration ---
[build]
  command = "npm run build"
  publish = "dist"

# --- Caching Headers for ONNX Model ---
[[headers]]
  for = "/models/student_model_float32.onnx"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/octet-stream"

# --- Caching Headers for Other Static Assets (JS, CSS, images, fonts) ---
[[headers]]
  for = "/*.{js,css,svg,png,jpg,jpeg,gif,woff,woff2,eot,ttf}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# --- Caching Headers for JSON files ---
[[headers]]
  for = "/test_split.json"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
